### ISSUE TITLE
Performance Pull request

### ISSUE THREAD

**Issue by ghost** [dbof10/react-native-snowfall#1]
We stumbled upon your package and did some performance upgrades. Since you layed the foundation, we would like to share the code. 

Tried to create a pull request, but it seems like your project is private.

Thanks for your work.

***Let it snow***

**Comment by dbof10** [comment]
Could you check it out?

**Comment by ghost** [comment]
Strangely enough I could. When I try to push I get this...

`
remote: Permission to dbof10/react-native-snowfall.git denied to felixus95.
fatal: unable to access 'https://github.com/dbof10/react-native-snowfall.git/': The requested URL returned error: 403
`

**Comment by ghost** [comment]
Created a fork, which worked. Pushing to your repository directly might not have been a intelligent choice from the beginning. :smile: 

Pull request is open. If you have questions, feel free to ask 😁

**Comment by dbof10** [comment]
Yes. you can't push directly into the repo even with other repos. With open source project, you have to fork, push your change and make a PR to an upstream repo
